### ISSUE TITLE
VSCode SFDX commands is creating executable files

### ISSUE THREAD

**Issue by rajeev-2020-arc** [forcedotcom/salesforcedx-templates#122]
Here the issue is when we are creating any files e.g. LWC, Apex Class, Visualforce Page from command platter of VS code it is getting created with executable permission, please refer below result:

npasalkar-ltm:pages npasalkar$ ls -l'
total 16
-rwxr-xr-x 1 npasalkar staff 155 Apr 27 22:45 testVFP.page
-rwxr-xr-x 1 npasalkar staff 171 Apr 27 22:45 testVFP.page-meta.xml
Same behaviour is also observe if I use below SFDX command to create an apex class:

>> sfdx force:apex:class:create -n myclass

Whereas if we create a file in VS code using "Right Click + New File" it is not getting created with executable permission, please refer below result:

npasalkar-ltm:pages npasalkar$ ls -l
total 16
-rw-r--r-- 1 npasalkar staff  0 Apr 27 22:46 testVFP2.page
Hence I want to understand is this behaviour is known to us, also is there any way to avoid creating a file with executable permission when using SFDX commands.

Any help or inputs will be highly appreciated.

**Comment by lcampos** [comment]
Thanks for opening this issue. The reason why this is happening is because the scaffolding command is using file templates that have those permissions. I think we can update those templates to only read and write access.
