### ISSUE TITLE
eslint-config-lwc 0.11.x requires @lwc/eslint-plugin-lwc as a peer dependency

### ISSUE THREAD

**Issue by khawkins** [forcedotcom/salesforcedx-templates#329]
### Summary

The update from `eslint-config-lwc` `v0.7.0` to `v0.11.0` (https://github.com/forcedotcom/salesforcedx-templates/pull/305) broke LWC linting in SFDX projects. This seems to be because `@lwc/eslint-plugin-lwc` is not getting installed as a peer at the top level of `node_modules`—though I'm not sure what changed between the two (besides configured versions) to make that happen.

### Steps To Reproduce:

1.  In a new VSCode window, open the command palette and select `SFDX: Create Project`. Select a `standard` project and save it.
1. Again from the command palette, select `SFDX: Create Lightning Web Component`, create a nominal component (e.g. `myLightningWebComponent`), and save it.
1.  From the command line, do a `yarn install` at the top of the project directory.
1. Execute the following from the command line:
    ```bash
    node_modules/.bin/eslint \
    force-app/main/default/lwc/myLightningWebComponent/myLightningWebComponent.js
    ```

### Expected result

For such a boilerplate LWC, no output (no linting failures).

### Actual result

```
Oops! Something went wrong! :(

ESLint: 7.27.0

ESLint couldn't find the plugin "@lwc/eslint-plugin-lwc".

(The package "@lwc/eslint-plugin-lwc" was not found when loaded as a Node module from the directory "/path/to/your/sfdx/project/force-app/main/default/lwc".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install @lwc/eslint-plugin-lwc@latest --save-dev

The plugin "@lwc/eslint-plugin-lwc" was referenced from the config file in "force-app/main/default/lwc/.eslintrc.json » @salesforce/eslint-config-lwc/recommended » /path/to/your/sfdx/project/node_modules/@salesforce/eslint-config-lwc/base.js".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
```

### Additional information

If I add:
```
"@lwc/eslint-plugin-lwc": "~1.0.0"
```
alongside the other `devDependencies` in the top-level `package.json`, this problem goes away.

**VS Code Version**: 1.56.2

**SFDX CLI Version**: sfdx-cli/7.81.0-7b953c80d1 darwin-x64 node-v12.18.3

**OS and version**: macOS Big Sur (11.3.1)

**Comment by khawkins** [comment]
Cc: @sfsholden and @pmdartus in case they have further insights into the issue.

It's worth noting that in the instructions of the [latest version](https://www.npmjs.com/package/@salesforce/eslint-config-lwc/v/2.0.0) of the `@salesforce/eslint-config-lwc` package, it recommends installing a number of peer dependencies (including `@lwc/eslint-plugin-lwc`) side by side as part of the installation process. Presumably some aspect of the internal configuration of the plugin/config packages made this necessary?

**Comment by pmdartus** [comment]
Yes, we were running into some strange installation issues with our previous setup. In fact, ESLint doesn't support loading plugins from within a config. You can find more details about this in https://github.com/salesforce/eslint-config-lwc/pull/58#issue-616192807.

I would recommend upgrading to `@salesforce/eslint-config-lwc` latest version and add the missing peer dependencies to the template to fix this issue. More details about the recent changes can be found in the [release](https://github.com/salesforce/eslint-config-lwc/releases) section.

**Comment by khawkins** [comment]
Thanks @pmdartus ! That's helpful. With that understanding, I might take a swing at a PR to update the template, and see if I can avoid breaking things further. 😉
