### ISSUE TITLE
prettier-plugin-apex devDependency version error in 7.122.1

### ISSUE THREAD

**Issue by Raspikabek** [forcedotcom/salesforcedx-templates#394]
### Summary

Execution of `npm install` command in new brand projects generated by `sfdx force:project:create` command fails the installation of `prettier-plugin-apex` version: 1.10.1 due to this version does not exists yet.

Updating the devDependency manually to `^1.10.0` works as expected.

List of latest versions of `prettier-plugin-apex`: https://www.npmjs.com/package/prettier-plugin-apex?activeTab=versions

### Steps To Reproduce:

1. Ensure you're running `sfdx-cli/7.122.1`
2. Create a new sfdx project by running `sfdx force:project:create -n my-awesome-project`
3. Inside the project run the command `npm install`

### Expected result

Installation of all packages successfully completed

### Actual result

```
npm ERR! notarget No matching version found for prettier-plugin-apex@^1.10.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### System Information

Run `sfdx version --verbose --json` and paste the output here.

```
{
        "cliVersion": "sfdx-cli/7.122.1",
        "architecture": "linux-x64",
        "nodeVersion": "node-v14.18.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.3 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/lwc-dev-server 2.11.0",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "@salesforce/sfdx-scanner 2.12.0",
                "alias 1.1.21 (core)",
                "apex 0.3.0 (core)",
                "auth 1.7.2 (core)",
                "config 1.2.40 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.2 (core)",
                "generator 1.2.0 (core)",
                "limits 1.2.2 (core)",
                "org 1.8.1 (core)",
                "salesforce-alm 52.6.0 (core)",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.122.1 (core)",
                "source 1.2.2 (core)",
                "telemetry 1.2.6 (core)",
                "templates 52.4.0 (core)",
                "trust 1.0.8 (core)",
                "user 1.5.0 (core)"
        ],
        "osVersion": "Linux 5.10.70-1-MANJARO"
}
```

**Comment by quinnmcphail** [comment]
It looks like @pozil fixed it in PR #353 about 3 months ago. I'm wondering if the CLI reverted somehow and is now grabbing an older template version.

**Comment by quinnmcphail** [comment]
After looking into this a bit more, it looks like the `main` and `develop` branches are not in sync. PR #374 is the PR that ended up changing the `prettier-plugin-apex` version from `^1.9.1` to `^1.10.1`.

That change never went through the `develop` branch. The `develop` branch contains the correct version of that specific dependency, but I don't think it includes a lot of other changes that have made it to the `main` branch.

I created a PR directly to `main` to decrement the version requirement, but I'm not sure if that's the best option.

**Comment by Raspikabek** [comment]
Small update: 

Still an issue in `sfdx-cli/7.133.0`

Same workaround applies to fix it, manual intervention after creation of a new project.

Any ETA around this? I've seen multiple comments and a PR created was closed and marked as 'solved' but is from October.

Thanks!

**Comment by quinnmcphail** [comment]
This appears to be fixed with the most recent release.

**Comment by Raspikabek** [comment]
I can confirm now in 7.139.0 this issue has been resolved.

I've created a new project from the scratch, version for Prettier Plugin Apex seems correct and the entire `npm install` command works flawlessly

**Comment by mohanraj-r** [comment]
Thanks for confirming the issue has been resolved @Raspikabek @quinnmcphail
