### ISSUE TITLE
Git tag missing for `@salesforce/templates` `v55.1.0`

### ISSUE THREAD

**Issue by edmorley** [forcedotcom/salesforcedx-templates#507]
The latest version of `@salesforce/templates` is `v55.1.0`:
https://www.npmjs.com/package/@salesforce/templates/v/55.1.0

However there is no Git tag for it, unlikely prior versions:
https://github.com/forcedotcom/salesforcedx-templates/tags

Also, the `package.json` in this repo still says `55.0.0` for version.

Seems like a release was performed locally and the code never pushed to the repo, or Git tagged?

This makes it hard to work out what's changed when reviewing eg Dependabot PRs.

**Comment by gbockus-sf** [comment]
updated the version and pushed the tag.

**Comment by edmorley** [comment]
@gbockus-sf Ah makes sense. Thank you!
